# Generated by Django 4.0 on 2022-07-03 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'введите более 3 символов')], verbose_name='Ингридиент')),
                ('unit_of_measurement', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(1, 'Введите название единицы измерения')], verbose_name='Единицы измерения')),
            ],
            options={
                'verbose_name': 'Ингридиент',
                'verbose_name_plural': 'Ингридиенты',
                'ordering': ('name',),
            },
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'unit_of_measurement'), name='ingredient_with_unit'),
        ),
    ]
