# Generated by Django 4.0 on 2022-07-09 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_ingredient_ingredient_with_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3, 'введите более 3 символов')], verbose_name='Ингридиент'),
        ),
    ]
