# Generated by Django 4.0 on 2022-07-10 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_name_alter_recipe_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, default='#', max_length=7, null=True, unique=True, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6})$', 'введите цветовой код в формате #F08080')], verbose_name='Цветовой HEX-код'),
        ),
    ]
