# Generated by Django 4.0 on 2022-07-09 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_alter_user_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3, 'введите более 3 символов'), django.core.validators.RegexValidator('^[a-zA-Zа-яА-Я]+$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3, 'введите более 3 символов'), django.core.validators.RegexValidator('^[a-zA-Zа-яА-Я]+$')], verbose_name='Фамилия'),
        ),
    ]
